apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsuite
  labels:
    app: gsuite
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gsuite
  template:
    metadata:
      name: gsuite
      labels:
        app: gsuite
    spec:
      containers:
        - name: gsuite
          image: vatusa/google-workspace-integration
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 25m
              memory: 50Mi
          command: ["/app/core"]
          envFrom:
            - secretRef:
                name: gsuite-secrets
      restartPolicy: Always