apiVersion: apps/v1
kind: Deployment
metadata:
  name: mithril
  labels:
    app: mithril
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mithril
  template:
    metadata:
      name: mithril
      labels:
        app: mithril
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mithril
                topologyKey: kubernetes.io/hostname
      containers:
        - name: mithril
          image: vatusa/mithril
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: mithril-secrets
            - configMapRef:
                name: mithril-config
      serviceAccountName: mithril-sa
      restartPolicy: Always
