apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status-vatusa-dev-tls
spec:
  dnsNames:
    - status.vatusa.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: status-vatusa-dev-tls
