apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base/api
- ../../base/discord-bot-v3
- ../../base/forums
- ../../base/google-workspace
- ../../base/www
- certificate.yaml
- api-ingress.yaml
- api-configmap.yaml
- www-ingress.yaml
- www-configmap.yaml
patches:
- path: www-deployment-patch.yaml
  target:
    kind: Deployment
    name: www
- path: api-deployment-patch.yaml
  target:
    kind: Deployment
    name: api
images:
- name: vatusa/api
  newName: vatusa/api
  newTag: 86c1a49f55e3338edba1e3e53fad36564c2a5da9
- name: vatusa/discord-bot-v3
  newName: vatusa/discord-bot-v3
  newTag: 1.1.18
- name: vatusa/forums
  newName: vatusa/forums
  newTag: 5b16e0884e1cd85b1b7e9f3e0a59fb3a8664405e
- name: vatusa/google-workspace-integration
  newName: vatusa/google-workspace-integration
  newTag: 1.1.37
- name: vatusa/www
  newName: vatusa/www
  newTag: a7c82078ddca9177ec5a3616a9e53edfe48ab0da
