apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teamspeak
spec:
  replicas: 1
  revisionHistoryLimit: 2
  serviceName: teamspeak
  selector:
    matchLabels:
      app: teamspeak
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: teamspeak
    spec:
      containers:
        - name: teamspeak
          image: teamspeak
          imagePullPolicy: IfNotPresent
          env:
            - name: TS3SERVER_LICENSE
              value: accept
            - name: TS3SERVER_QUERY_PROTOCOLS
              value: raw,ssh
          ports:
            - containerPort: 9987
              hostPort: 9987
              name: udp9987
              protocol: UDP
            - containerPort: 10011
              hostPort: 10011
              name: tcp10011
              protocol: TCP
            - containerPort: 30033
              hostPort: 30033
              name: tcp30033
              protocol: TCP
          volumeMounts:
            - mountPath: /var/ts3server
              name: teamspeak-data
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - /var/ts3server/update-ip.sh
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      volumes:
        - name: do-teamspeak-data
          persistentVolumeClaim:
            claimName: do-teamspeak-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
