apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- certificate.yaml
- portal-ingress.yaml
- staff-ingress.yaml
- configmap.yaml
images:
- name: vatusa/portal
  newName: vatusa/portal
  newTag: bba3e0cb737086c3e02fec9c7b0fbe4570c5771d
- name: vatusa/staff
  newName: vatusa/staff
  newTag: fb0648eed814228f7c41efdec54645c20cfee566
