apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- certificate.yaml
- portal-ingress.yaml
- staff-ingress.yaml
- configmap.yaml
images:
- name: vatusa/portal
  newName: vatusa/portal
  newTag: 68bcee49f63ec6ec77f3b085c8852710500af82e
- name: vatusa/staff
  newName: vatusa/staff
  newTag: 68bcee49f63ec6ec77f3b085c8852710500af82e
