apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- certificate.yaml
- portal-ingress.yaml
- staff-ingress.yaml
- configmap.yaml
patches:
- path: portal-replicas-patch.yaml
  target:
    kind: Deployment
    name: portal
- path: staff-replicas-patch.yaml
  target:
    kind: Deployment
    name: staff
images:
- name: vatusa/portal
  newName: vatusa/portal
  newTag: 3a6d54acee93e4d509b1d45bd1e7312c516f4dd2
- name: vatusa/staff
  newName: vatusa/staff
  newTag: 7381bfadd1b7444f438f3869b9cd5f2e63966a10
