apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
  labels:
    app: portal
data:
  NODE_ENV: "development"
  VATUSA_DISCORD_INVITE_URL: "https://discord.gg/a7Qcse7"
  NEXT_PUBLIC_SUPPORT_TICKET_URL: ""
  COBALT_BASE_URL: "https://vatusa.dev/cobalt"