apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/auth-proxy
  newName: vatusa/auth-proxy
  newTag: d60861e9c3a970d326f3079ec9943363fe8cc3e5
- name: vatusa/myvatusa
  newName: vatusa/myvatusa
  newTag: cb8c417542ec7b416c62746095f4cceeb593aed4
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: bbdee21ef4b0529354ca7c8ebaa114488d367645
