apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/auth-proxy
  newName: vatusa/auth-proxy
  newTag: 4582373c813860a70cb4ca1b83d3293e4ecfb9cb
- name: vatusa/myvatusa
  newName: vatusa/myvatusa
  newTag: cb8c417542ec7b416c62746095f4cceeb593aed4
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: 488514faa7c479a62083f1fe559817ed6cd80c92
