apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/auth
  newName: vatusa/auth
  newTag: 3c3b440684d0cb289b1e203df91ee8bd7b0e21cf
- name: vatusa/myvatusa
  newName: vatusa/myvatusa
  newTag: cb8c417542ec7b416c62746095f4cceeb593aed4
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: b1001fb
