apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: 29f248f71c3c34828895108ad49861708d098846
