apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/auth
  newName: vatusa/auth
  newTag: 92480de9710c4befe468824abc9c4dcc45ca3af5
- name: vatusa/myvatusa
  newName: vatusa/myvatusa
  newTag: 5a4ca894e55081083ee6be945731bd28eb4b49ea
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: "7811870"
