apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/auth
  newName: vatusa/auth
  newTag: 6d868e47522d28f6d0be91e75de49c32f6ceabea
- name: vatusa/frontend
  newName: vatusa/frontend
  newTag: 666907165940f6372e0aad8b18f541e15fe93092
- name: vatusa/myvatusa
  newName: vatusa/myvatusa
  newTag: 03e9b0044a0edfdfe546701d6382b75f9a0c19f9
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: b211f8e
