apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: 13a99c2eb0af386e803178159cfc9a4974135cb8
