apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/primary-api
  newName: vatusa6tech/primary-api
  newTag: 44a951e46673304fc2eefc181b924266a3c3e7ab
