apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: vatusa/auth
  newName: vatusa/auth
  newTag: 6d868e47522d28f6d0be91e75de49c32f6ceabea
- name: vatusa/frontend
  newName: vatusa/frontend
  newTag: 666907165940f6372e0aad8b18f541e15fe93092
- name: vatusa/myvatusa
  newName: vatusa/myvatusa
  newTag: 26493039464937b72ba3a4ee8642d30b3e6714a8
- name: vatusa/primary-api
  newName: vatusa/primary-api
  newTag: fa5b4ae
