apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bot-vatusa-net-tls
spec:
  dnsNames:
    - bot.vatusa.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: bot-vatusa-net-tls