- op: replace
  path: /spec/replicas
  value: 1
- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: 15m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
