apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base/api
- ../../base/www
- certificate.yaml
- api-ingress.yaml
- api-configmap.yaml
- www-ingress.yaml
- www-configmap.yaml
- eso-service-account.yaml
- eso-secret-store.yaml
- www-secrets-es.yaml
- api-secrets-es.yaml
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: www
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: api
- path: api-worker-scale-patch.yaml
  target:
    kind: Deployment
    name: api-worker
- path: www-worker-scale-patch.yaml
  target:
    kind: Deployment
    name: www-worker
images:
- name: vatusa/api
  newName: vatusa/api
  newTag: 72b5fea59b5679e5beec9f6f9cd6d9c69421d953
- name: vatusa/discord-bot-v3
  newName: vatusa/discord-bot-v3
  newTag: 1.1.17
- name: vatusa/google-workspace-integration
  newName: vatusa/google-workspace-integration
  newTag: 1.1.35
- name: vatusa/www
  newName: vatusa/www
  newTag: 061f09a93389cbfc93de3f376ef169c8a4dad197
