apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base/api
- ../../base/www
- certificate.yaml
- api-ingress.yaml
- api-configmap.yaml
- www-ingress.yaml
- www-configmap.yaml
- eso-service-account.yaml
- eso-secret-store.yaml
- www-secrets-es.yaml
- api-secrets-es.yaml
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: www
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: api
- path: api-deployment-patch.yaml
  target:
    kind: Deployment
    name: api
- path: api-scale-patch.yaml
  target:
    kind: Deployment
    name: api
- path: api-queue-scale-patch.yaml
  target:
    kind: Deployment
    name: api-queue
- path: api-worker-scale-patch.yaml
  target:
    kind: Deployment
    name: api-worker
- path: www-worker-scale-patch.yaml
  target:
    kind: Deployment
    name: www-worker
images:
- name: vatusa/api
  newName: vatusa/api
  newTag: c093fc3fe81939d99d76e69240a4f211401b64c7
- name: vatusa/discord-bot-v3
  newName: vatusa/discord-bot-v3
  newTag: 1.1.17
- name: vatusa/google-workspace-integration
  newName: vatusa/google-workspace-integration
  newTag: 1.1.35
- name: vatusa/www
  newName: vatusa/www
  newTag: 6685e5ceaa5cff98b41ecd51e68a15c6e1d2f760
