apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: www-secrets-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bao-eso
    kind: SecretStore
  target:
    name: www-secrets
  dataFrom:
    - extract:
        key: secret/data/legacy/dev/db