apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- base
images:
- name: vatusa/api
  newName: vatusa/api
  newTag: 7564b5f341521212d3c3ee1871e07d1190461fef
- name: vatusa/discord-bot-v3
  newName: vatusa/discord-bot-v3
  newTag: 1.1.17
- name: vatusa/forums
  newName: vatusa/forums
  newTag: 5b16e0884e1cd85b1b7e9f3e0a59fb3a8664405e
- name: vatusa/google-workspace-integration
  newName: vatusa/google-workspace-integration
  newTag: 1.1.37
- name: vatusa/www
  newName: vatusa/www
  newTag: 7c0916cc4599aef2f9e4bd56e0af60e4d55aad70
