apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: current
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/vatusa/gitops'
  destinations:
    - namespace: current
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceBlacklist:
    - group: 'networking.k8s.io'
      kind: 'NetworkPolicy'