apiVersion: apps/v1
kind: Deployment
metadata:
  name: zan-site
  labels:
    app: zan-site
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: zan-site
  template:
    metadata:
      name: zan-site
      labels:
        app: zan-site
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - zan-site
                topologyKey: kubernetes.io/hostname
      containers:
        - name: zan-site
          image: vatusa/zan-site
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: zan-site-config
      restartPolicy: Always
