apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxy-vatusa-dev-tls
spec:
  dnsNames:
    - api.vatusa.dev
    - sso.vatusa.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: proxy-vatusa-dev-tls
