apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/certificate.yaml
- base/deployment.yaml
- base/ingress.yaml
- base/ingress-inline.yaml
- base/service.yaml
- base/service-account.yaml
- base/service-account-bindings.yaml
images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: 563cf4747e5afbda13872cce1efd2b13bee28b55
