apiVersion: v1
data:
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, logs, get, *, allow
    p, role:org-admin, exec, create, */*, allow

    g, vatusa:admin, role:ngws

    p, vatusa:zdv, projects, get, zdv, allow
    p, vatusa:zdv, applications, *, zdv/*, allow
    p, vatusa:zdv, repositories, get, zdv/*, allow
    p, vatusa:zdv, logs, get, zdv/*, allow
    p, vatusa:zdv, exec, create, zdv/*, allow
    p, vatusa:zdv, projects, get, *, deny
    p, vatusa:zdv, applications, *, */*, deny

    p, vatusa:zlc, projects, get, zlc, allow
    p, vatusa:zlc, applications, *, zlc/*, allow
    p, vatusa:zlc, repositories, get, zlc/*, allow
    p, vatusa:zlc, logs, get, zlc/*, allow
    p, vatusa:zlc, exec, create, zlc/*, allow
    p, vatusa:zlc, projects, get, *, deny
    p, vatusa:zlc, applications, *, */*, deny
    
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
