ingress-nginx:
  controller:
    kind: DaemonSet
    config:
      proxy-body-size: 128m
      use-forwarded-headers: "true"
    service:
      externalTrafficPolicy: Local
      ipFamilyPolicy: RequireDualStack
      ipFamilies:
        - IPv4
        - IPv6