apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap-api.yaml
- configmap-site.yaml
- certificate.yaml
- ingress-site.yaml
- ingress-api.yaml
- eso-service-account.yaml
- eso-secret-store.yaml
- zan-api-secrets-es.yaml
patches:
- path: site-replicas-patch.yaml
  target:
    kind: Deployment
    name: zan-site
images:
- name: vatusa/zan-api
  newName: vatusa/zan-api
  newTag: latest
- name: vatusa/zan-site
  newName: vatusa/zan-site
  newTag: latest
