apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ngws-project
resources:
  - namespace.yaml
  - Project.yaml
  - ../allow-apis.yaml
  - ../allow-db.yaml
  - ../allow-dns.yaml
  - ../deny-egress.yaml