global:
  security:
    allowInsecureImages: true
    
rabbitmq:
  image:
    registry: public.ecr.aws
    repository: bitnami/rabbitmq

  auth:
    username: admin
    existingPasswordSecret: passwords
  primary:
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 375m
