apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-vatusa-net-tls
spec:
  dnsNames:
    - auth.vatusa.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: auth-vatusa-net-tls
