apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apis
  namespace: zkc
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          cidr: 172.67.68.102/32 # data.vatsim.net
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 172.67.135.197/32 # api.vatusa.net
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 13.107.213.57/32 # aviationweather.gov
      ports:
        - protocol: TCP
          port: 443
