apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vatusa-dev-tls
spec:
  dnsNames:
    - vatusa.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: vatusa-dev-tls