apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-vatusa-dev-tls
spec:
  dnsNames:
    - my.vatusa.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: my-vatusa-dev-tls