apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vatusa-dev-tls
spec:
  dnsNames:
    - azure.vatusa.dev
    - www.azure.vatusa.dev
    - api.azure.vatusa.dev
    - login.azure.vatusa.dev
    - auth.azure.vatusa.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: vatusa-dev-tls
