apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forums-vatusa-net-tls
spec:
  dnsNames:
    - forums.vatusa.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: forums-vatusa-net-tls