image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
useDeploy: true
service:
  port: 3001
  nodePort:
  annotations: {}
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
  hosts:
    - host: status.vatusa.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: uptime-kuma-tls
      hosts:
        - status.vatusa.dev
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 180
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
  exec:
    command:
      - "extra/healthcheck"
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
  exec:
    command: []
  httpGet:
    path: /
    port: 3001
    scheme: HTTP
    httpHeaders: []
volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 4Gi
strategy:
  type: Recreate