replicaCount: 1
image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag:
service:
  port: 3001
persistence:
  enabled: true
  size: 10Gi
  storageClassName: ""
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
  hosts:
    - host: status.vatusa.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: uptime-kuma-tls
      hosts:
        - status.vatusa.dev
resources:
  requests:
    memory: 50Mi
    cpu: 50m
  limits:
    memory: 100Mi
    cpu: 150m
env:
  TZ: "America/Chicago"
monitorUrls: |
  - type: url
    url: https://zdvartcc.org
    interval: 60 # Seconds
  - type: url
    url: https://zlcartcc.org
    interval: 60
