apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff
  labels:
    app: staff
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: staff
  template:
    metadata:
      name: staff
      labels:
        app: staff
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - staff
                topologyKey: kubernetes.io/hostname
      containers:
        - name: staff
          image: vatusa/staff
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: webapps-secrets
            - configMapRef:
                name: webapps-config
      restartPolicy: Always
