apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: mithril-ingress
- path: certificate-patch.yaml
  target:
    kind: Certificate
    name: mithril-tls
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: mithril
images:
- name: vatusa/mithril
  newName: vatusa/mithril
  newTag: 37674d84d8528250e1970fa1c8e121c52a718a67
