apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: mithril-ingress
- path: certificate-patch.yaml
  target:
    kind: Certificate
    name: mithril-tls
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: mithril
images:
- name: vatusa/mithril
  newName: vatusa/mithril
  newTag: f055db3a731ddb659a2c344c474ebcb77a1f248f
