apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: mithril-ingress
- path: certificate-patch.yaml
  target:
    kind: Certificate
    name: mithril-tls
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: mithril
images:
- name: vatusa/mithril
  newName: vatusa/mithril
  newTag: 6250c35c96cbc0e9181a8692930b10be0d6934d3
