apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- certificate.yaml
- portal-ingress.yaml
- staff-ingress.yaml
- configmap.yaml
- portal-pdb.yaml
- staff-pdb.yaml
images:
- name: vatusa/portal
  newName: vatusa/portal
  newTag: 6cc40fdb1940141c590dc8ef68cce641dc47dac8
- name: vatusa/staff
  newName: vatusa/staff
  newTag: 6cc40fdb1940141c590dc8ef68cce641dc47dac8
