apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- certificate.yaml
- portal-ingress.yaml
- staff-ingress.yaml
- configmap.yaml
- portal-pdb.yaml
- staff-pdb.yaml
images:
- name: vatusa/portal
  newName: vatusa/portal
  newTag: 64449e256a7a39e6a9c2703de7886d420155a2a3
- name: vatusa/staff
  newName: vatusa/staff
  newTag: 64449e256a7a39e6a9c2703de7886d420155a2a3
