apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
- pdb.yaml

images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: d13af93929dd48da0509a9081798db70b2fa1e0a
