apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml

images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: 45befa29c70700e426dede9e9f5b619a5b3686e2
