apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
- pdb.yaml

images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: 38d60f4e898f28b60afe33386f15af5d3c9d6185
