apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhp-discord-bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: adhp-discord-bot
  template:
    metadata:
      labels:
        app: adhp-discord-bot
    spec:
      containers:
        - name: adhp-discord-bot
          image: adhp/bot:e43578f
          volumeMounts:
            - name: config-volume
              mountPath: /etc/bot/config.yaml
              subPath: config.yaml
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 250m
              memory: 500Mi
      volumes:
        - name: config-volume
          secret:
            secretName: adhp-discord-bot-secrets