apiVersion: v1
kind: ConfigMap
metadata:
  name: cobalt-config
  labels:
    app: cobalt
data:
  APP_ENV: "staging"
  APP_BASE_URL: "https://cobalt.vatusa.dev/"
  POST_LOGIN_URL: "https://vatusa.dev/auth/callback"
  VATSIM_API2_URL: "https://api.vatsim.net/v2"

