apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: cobalt-ingress
- path: ingress-inline-patch.yaml
  target:
    kind: Ingress
    name: cobalt-inline-ingress
- path: certificate-patch.yaml
  target:
    kind: Certificate
    name: cobalt-tls
images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: 6cf2184bb914a766a856438028045b4523693c12
