apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
patches:
- path: replicas-patch.yaml
  target:
    kind: Deployment
    name: cobalt
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: cobalt-ingress
- path: certificate-patch.yaml
  target:
    kind: Certificate
    name: cobalt-tls
- path: ingress-inline-patch.yaml
  target:
    kind: Ingress
    name: cobalt-inline-ingress
images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: 38d60f4e898f28b60afe33386f15af5d3c9d6185
