apiVersion: v1
kind: ConfigMap
metadata:
  name: mithril-config
  labels:
    app: mithril
data:
  APP_ENV: "prod"
  APP_BASE_URL: "https://mithril.vatusa.net/"
  POST_LOGIN_URL: "https://vatusa.net/"
  VATSIM_API2_URL: "https://api.vatsim.net/v2"
