apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
- pdb.yaml
images:
- name: vatusa/mithril
  newName: vatusa/mithril
  newTag: ff30728aed50484018ad96ae66da62105c3c97a5
