apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
- pdb.yaml
images:
- name: vatusa/mithril
  newName: vatusa/mithril
  newTag: 5b0e38385dcefe7c8225d90ba081cb32d1e66e18
