apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- configmap.yaml
- pdb.yaml
images:
- name: vatusa/mithril
  newName: vatusa/mithril
  newTag: 17e50e8ad27720dfb6b328656ab7ed48b500227f
