apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-cronjob
spec:
  schedule: '* * * * *'  # Adjust the cron schedule as needed
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-cron
              image: vatusa/api:bdf94cc
              imagePullPolicy: IfNotPresent
              command:
                - php
              args:
                - artisan
                - schedule:run
              envFrom:
                - secretRef:
                    name: api-secrets
                - configMapRef:
                    name: api-config
              workingDir: /www
              tty: true
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  suspend: false
