apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: configs
resources:
  - base/argocd-ingress.yaml
  - base/argocd-rbac-cm.yaml
  - base/argocd-namespace-creator.yaml
  - base/argocd-namespace-creator-binding.yaml
  - base/cert-manager-ClusterIssuer.yaml
  - base/rabbitmq-ingress.yaml
  - base/rabbitmq-service.yaml