apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: canvas-vatusa-dev-tls
spec:
  dnsNames:
    - canvas.vatusa.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: canvas-vatusa-dev-tls
