apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-headless
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: valkey
