name: Common Dev Deploy Workflow
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      kustomization-folder:
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to ArgoCD
    uses: ./.github/workflows/common-gitops-bump.yml
    with:
      image-name: ${{ inputs.image-name }}
      kustomization-folder: ${{ inputs.kustomization-folder }}
      overlay: dev
      tag: ${{ github.sha }}
    secrets: inherit
